### ISSUE TITLE
No source found on (Arch)Linux

### ISSUE THREAD

**Issue by pschichtel** [Palakis/obs-ndi#104]
I installed the AUR packages libndi3-bin and obs-ndi and started OBS. The plugin gets successfully loaded, output seems to work (network ports bound and CPU load increases as it would when streaming).
The problem: When I create an NDI Source, the dialog will not show any source names, not even the output on the same system. Doing the same on Windows system works, but the Linux system won't get the Windows system's source. It also doesn't work between two Linux systems.

I tested it with a normal user and root, no difference. The log shows no errors except for the "can't create a receiver for NDI source" line which is expected as the "Source name" field stays empty.

**Comment by pschichtel** [comment]
Also: The Windows system doesn't see the source from a Linux machine

**Comment by pschichtel** [comment]
```
error: [obs-ndi] can't create a receiver for NDI source ''

Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
__pthread_join (threadid=0, thread_return=0x0) at pthread_join.c:45
45	  if (INVALID_NOT_TERMINATED_TD_P (pd))
(gdb) thread apply 1 bt full

Thread 1 (Thread 0x7ffff7f9a600 (LWP 2859)):
#0  0x00007ffff34d985e in __pthread_join (threadid=0, thread_return=0x0) at pthread_join.c:45
        pd = 0x0
        self = <optimized out>
        result = <optimized out>
#1  0x00007fffb9032033 in ndi_source_destroy(void*) () at /usr//lib/obs-plugins/obs-ndi.so
#2  0x00007ffff4efce2f in obs_source_destroy (source=0x5555566937e0) at /home/phillip/tmp/obs-studio/trunk/src/obs-studio-21.0.2/libobs/obs-source.c:542
        i = <optimized out>
#3  0x00007ffff4efd6cd in obs_source_release (source=<optimized out>) at /home/phillip/tmp/obs-studio/trunk/src/obs-studio-21.0.2/libobs/obs-source.c:621
        control = 0x555556694740
#4  0x00007ffff4f0f094 in obs_load_sources (array=0x555556623b80, cb=0x5555555dda70, private_data=0x555555c44450)
    at /home/phillip/tmp/obs-studio/trunk/src/obs-studio-21.0.2/libobs/obs.c:1628
        sources = 
            {da = {array = 0x555556695f60, num = <optimized out>, capacity = <optimized out>}, {array = 0x555556695f60, num = <optimized out>, capacity = <optimized out>}}
        count = <optimized out>
        i = <optimized out>
#5  0x00005555555f78a6 in  ()
#6  0x0000012c04000001 in  ()
#7  0x000055555661fd80 in  ()
#8  0x00007fffffffcd70 in  ()
#9  0x000055555661ff20 in  ()
#10 0x0000555556623b80 in  ()
#11 0x0000555556622ea0 in  ()
#12 0x00005555565fe8b0 in  ()
#13 0x00007fffffffcc18 in  ()
#14 0x000055555661fe40 in  ()
#15 0x0000555555c44450 in  ()
#16 0x0000555555c5fae0 in  ()
#17 0x00007ffff4eeee9d in profile_start (name=<optimized out>) at /home/phillip/tmp/obs-studio/trunk/src/obs-studio-21.0.2/libobs/util/profiler.c:392
        new_call = 
          {name = 0x5555556c7853 "OBSBasic::Load", start_time = 0, end_time = 0, expected_time_between_calls = 0, children = {da = {array = 0x0, num = 1542447832124994560, capacity = 0}, {array = 0x0, num = 1542447832124994560, capacity = 0}}, parent = 0x555555c44450}
        call = 0x5555565fec00
#18 0x00005555555ff0f6 in  ()
#19 0x0000555555c67680 in  ()
#20 0x000055555659bb70 in  ()
#21 0x0000555555c774a0 in  ()
#22 0x00007fff00000001 in  ()
#23 0x00007ffff46dd251 in  () at /usr/lib/libQt5Core.so.5
#24 0x0000000000000001 in  ()
#25 0x0000555555c67680 in  ()
#26 0x00007fffffffcd30 in  ()
#27 0x0000555555c67680 in  ()
#28 0x0000000000000000 in  ()
```
This now happens when I try to start OBS.

**Comment by pschichtel** [comment]
No OBS crashed when exiting:

```
Process 30955 (obs) of user 1000 dumped core.
                                                       
Stack trace of thread 30955:
#0  0x00007fe4293b9c7b avahi_threaded_poll_stop (libavahi-common.so.3)
#1  0x00007fe4296310da n/a (libndi.so.3)
#2  0x00007fe429627402 n/a (libndi.so.3)
#3  0x00007fe4295e34c3 NDIlib_send_destroy (libndi.so.3)
#4  0x00007fe429ba16e1 _Z15ndi_output_stopPvm (obs-ndi.so)
#5  0x00007fe4658b5f40 obs_output_actual_stop (libobs.so.0)
#6  0x00007fe4658b6336 obs_output_destroy (libobs.so.0)
#7  0x00007fe4658b6ca5 obs_output_release (libobs.so.0)
#8  0x00007fe429b9f58e _Z16main_output_stopv (obs-ndi.so)
#9  0x0000555e3da10e98 _ZN12OBSStudioAPI8on_eventE18obs_frontend_event (obs)
#10 0x0000555e3da2f331 _ZN8OBSBasic10closeEventEP11QCloseEvent (obs)
#11 0x00007fe4680bde38 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
#12 0x00007fe4681d6861 _ZN11QMainWindow5eventEP6QEvent (libQt5Widgets.so.5)
#13 0x00007fe46807de3c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
#14 0x00007fe468085816 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
#15 0x00007fe464c206c0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
#16 0x00007fe4680b9017 _ZN14QWidgetPrivate12close_helperENS_9CloseModeE (libQt5Widgets.so.5)
#17 0x00007fe4680bcf5b n/a (libQt5Widgets.so.5)
#18 0x00007fe464c50ee6 _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
#19 0x00007fe468077383 _ZN7QAction9triggeredEb (libQt5Widgets.so.5)
#20 0x00007fe468079c06 _ZN7QAction8activateENS_11ActionEventE (libQt5Widgets.so.5)
#21 0x00007fe4681ffc45 n/a (libQt5Widgets.so.5)
#22 0x00007fe46820730c n/a (libQt5Widgets.so.5)
#23 0x00007fe468208174 _ZN5QMenu17mouseReleaseEventEP11QMouseEvent (libQt5Widgets.so.5)
#24 0x00007fe4680bde38 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
#25 0x00007fe46820a4ac _ZN5QMenu5eventEP6QEvent (libQt5Widgets.so.5)
#26 0x00007fe46807de3c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
#27 0x00007fe468085d91 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
#28 0x00007fe464c206c0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
#29 0x00007fe468084d1a _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Eb (libQt5Widgets.so.5)
#30 0x00007fe4680d8fb7 n/a (libQt5Widgets.so.5)
#31 0x00007fe4680db9a0 n/a (libQt5Widgets.so.5)
#32 0x00007fe46807de3c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
#33 0x00007fe468085816 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
#34 0x00007fe464c206c0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
#35 0x00007fe465191634 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE (libQt5Gui.so.5)
#36 0x00007fe465193186 _ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE (libQt5Gui.so.5)
#37 0x00007fe46516abbc _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5)
#38 0x00007fe452da22fd n/a (libQt5XcbQpa.so.5)
#39 0x00007fe464c1ed0b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#40 0x00007fe464c27ff8 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
#41 0x0000555e3da06a59 run_program (obs)
#42 0x00007fe463ae7f2a __libc_start_main (libc.so.6)
#43 0x0000555e3da07baa _start (obs)
```

The fact that it crashed in libavahi-common.so suggested that it might need the avahi daemon running. Starting the avahi daemon did indeed solve all problems, so I guess the plugin should depend on avahi and might suggest starting it in the documentation.

**Comment by luki9100** [comment]
hey, I´m using Arch linux and i startet the avahi deamon with "systemctl start avahi-daemon.service" but obs still crashes when launching with " can´t create a receiver for NDI source  "" "

**Comment by pschichtel** [comment]
Well the avahi service doesn't fix this crash, it just prevents it from 
happening. The crash happens because the stored NDI source has an empty 
source name. You have to manually remove it from your scene JSON to get obs 
running again. Or temporarily uninstall the plugin.



Am 14. Februar 2018 16:34:50 schrieb luki9100 <notifications@github.com>:

**Comment by dx9s** [comment]
This this is the same issue I am experiencing https://github.com/Palakis/obs-ndi/issues/128

**Comment by pschichtel** [comment]
I think the main porblem here, the missing avahi service, is sovled. I suggested adding avahi as a dependency to the relevant AUR packages.
@Palakis you might want to document the dependency in case other people face this issue.
